#!/usr/bin/env python
# -*- coding: utf-8 -*-

from distutils.core import \
    setup, \
    Extension


setup(
    ext_modules=[Extension('mapdamage.seqtk',
                           sources=['mapdamage/seqtk/seqtkmodule.c'],
                           depends=['mapdamage/seqtk/kseq.h'])],
    name='mapdamage',
    version='2.1',
    author='Aurélien Ginolhac, Mikkel Schubert, Hákon Jónsson',
    author_email='MSchubert@snm.ku.dk, jonsson.hakon@gmail.com',
    packages=['mapdamage'],
    package_data={'mapdamage': ['Rscripts/*.R','Rscripts/stats/*.R','seqtk/seqtk']},
    scripts=['bin/mapDamage'],
    url='https://github.com/ginolhac/mapDamage',
    license='LICENSE.txt',
    description='mapDamage tracks and quantify DNA damage pattern among ancient DNA sequencing reads generated by Next-Generation Sequencing platforms',
    long_description=open('README.md').read()
)
