#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import codecs

from setuptools import setup, Extension


def _get_version():
    """Retrieve version from current install directory."""
    env = {}
    with open(os.path.join("mapdamage", "__init__.py")) as handle:
        exec(handle.read(), env)

    return env["__version__"]


def _get_readme():
    """Retrieves contents of README.rst, forcing UTF-8 encoding."""
    with codecs.open("README.md", encoding="utf-8") as handle:
        return handle.read()


setup(
    name='mapdamage',
    version=_get_version(),

    description='mapDamage tracks and quantify DNA damage pattern among '
                'ancient DNA sequencing reads generated by Next-Generation '
                'Sequencing platforms',
    long_description=_get_readme(),
    url='https://github.com/ginolhac/mapDamage',

    author='Aurélien Ginolhac, Mikkel Schubert, Hákon Jónsson',
    author_email='MSchubert@snm.ku.dk, jonsson.hakon@gmail.com',

    license='MIT',

    packages=['mapdamage'],
    package_data={'mapdamage': ['Rscripts/*.R',
                                'Rscripts/stats/*.R']},

    install_requires=['pysam>=0.9.1'],
    ext_modules=[Extension('mapdamage.seqtk',
                           sources=['mapdamage/seqtk/seqtkmodule.c'],
                           depends=['mapdamage/seqtk/kseq.h'])],

    include_package_data=True,

    entry_points={
        'console_scripts': [
            'mapDamage=mapdamage.main:main',
        ],
    },
)
